language: ruby
rvm:
  - 2.6.3

install:
  - bundle install
  - gem install jekyll
  - gem install jekyll-scholar
  - gem install jekyll-pandoc
  - gem install jekyll-paginate-v2
  - gem install jekyll-feed

branches:
  only:
    - master

cache: bundler

env:
  global:
    - JEKYLL_ENV=production

notifications:
  email:
    recipients:
      - stefangroth@me.com
    on_success: always
    on_failure: always

script:
  - chmod +x _scripts/build.sh
  - _scripts/build.sh

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "stefangroth.com"
    region: $AWS_DEFAULT_REGION
    skip_cleanup: true
    local_dir: _site
    on:
      branch: master

sudo: false
addons:
  apt:
    packages:
      - sshpass
